# Generated by Django 3.1.2 on 2021-02-10 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
