# Generated by Django 3.1.2 on 2021-02-11 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_cart_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
